// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Tambah
        /// </summary>
        public void Tambah()
        {
            #region Variable Declarations
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(32, 20));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(24, 10));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(23, 25));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 18));
        }
        
        /// <summary>
        /// Kurang - Use 'KurangParams' to pass parameters into this method.
        /// </summary>
        public void Kurang()
        {
            #region Variable Declarations
            WpfEdit uITBEdit = this.UIMyCalculatorv1Window.UITBEdit;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Type '5' in 'tb' text box
            uITBEdit.Text = this.KurangParams.UITBEditText;

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(33, 19));

            // Type '33' in '-' button
            Keyboard.SendKeys(uIItemButton3, this.KurangParams.UIItemButton3SendKeys, ModifierKeys.None);

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(21, 19));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(72, 6));
        }
        
        /// <summary>
        /// Bagi
        /// </summary>
        public void Bagi()
        {
            #region Variable Declarations
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(20, 25));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(11, 16));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(33, 26));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 9));
        }
        
        /// <summary>
        /// Kali
        /// </summary>
        public void Kali()
        {
            #region Variable Declarations
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton5 = this.UIMyCalculatorv1Window.UIItemButton5;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(35, 18));

            // Click '*' button
            Mouse.Click(uIItemButton5, new Point(43, 21));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(32, 12));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 22));
        }
        
        #region Properties
        public virtual KurangParams KurangParams
        {
            get
            {
                if ((this.mKurangParams == null))
                {
                    this.mKurangParams = new KurangParams();
                }
                return this.mKurangParams;
            }
        }
        
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private KurangParams mKurangParams;
        
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Kurang'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class KurangParams
    {
        
        #region Fields
        /// <summary>
        /// Type '5' in 'tb' text box
        /// </summary>
        public string UITBEditText = "5";
        
        /// <summary>
        /// Type '33' in '-' button
        /// </summary>
        public string UIItemButton3SendKeys = "33";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.Name] = "9";
                    this.mUIItem9Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfEdit UITBEdit
        {
            get
            {
                if ((this.mUITBEdit == null))
                {
                    this.mUITBEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITBEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tb";
                    this.mUITBEdit.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUITBEdit;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItem8Button
        {
            get
            {
                if ((this.mUIItem8Button == null))
                {
                    this.mUIItem8Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem8Button.SearchProperties[WpfButton.PropertyNames.Name] = "8";
                    this.mUIItem8Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem8Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItem7Button
        {
            get
            {
                if ((this.mUIItem7Button == null))
                {
                    this.mUIItem7Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem7Button.SearchProperties[WpfButton.PropertyNames.Name] = "7";
                    this.mUIItem7Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem7Button;
            }
        }
        
        public WpfButton UIItemButton5
        {
            get
            {
                if ((this.mUIItemButton5 == null))
                {
                    this.mUIItemButton5 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton5.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton5.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton5;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfEdit mUITBEdit;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItem8Button;
        
        private WpfButton mUIItemButton4;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItem7Button;
        
        private WpfButton mUIItemButton5;
        
        private WpfButton mUIItem5Button;
        #endregion
    }
}
